# Generated by Django 3.0.4 on 2020-03-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='kyc_doc1',
            field=models.FileField(blank=True, null=True, upload_to='DoctorKYC/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='kyc_doc2',
            field=models.FileField(blank=True, null=True, upload_to='DoctorKYC/'),
        ),
        migrations.CreateModel(
            name='LabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_lab1', models.FileField(blank=True, null=True, upload_to='DoctorKYC/')),
                ('kyc_lab2', models.FileField(blank=True, null=True, upload_to='DoctorKYC/')),
                ('is_kyc_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_chem1', models.FileField(blank=True, null=True, upload_to='DoctorKYC/')),
                ('kyc_chem2', models.FileField(blank=True, null=True, upload_to='DoctorKYC/')),
                ('is_kyc_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
