# Generated by Django 3.0.4 on 2020-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_entities', '0002_auto_20200328_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='kyc_chem1',
            field=models.FileField(blank=True, null=True, upload_to='ChemistKYC/'),
        ),
        migrations.AlterField(
            model_name='chemist',
            name='kyc_chem2',
            field=models.FileField(blank=True, null=True, upload_to='ChemistKYC/'),
        ),
        migrations.AlterField(
            model_name='labuser',
            name='kyc_lab1',
            field=models.FileField(blank=True, null=True, upload_to='LabUSerKYC/'),
        ),
        migrations.AlterField(
            model_name='labuser',
            name='kyc_lab2',
            field=models.FileField(blank=True, null=True, upload_to='LabUSerKYC/'),
        ),
    ]
