# Generated by Django 3.0.4 on 2020-04-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_entities', '0003_auto_20200328_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_pat1', models.FileField(blank=True, null=True, upload_to='PatientKYC/')),
                ('kyc_pat2', models.FileField(blank=True, null=True, upload_to='PatientKYC/')),
                ('is_kyc_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
