# Generated by Django 3.0.4 on 2020-03-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
